export const GET_REQUEST = "FETCH_REQUEST";

export const SET_ACCOUNT = "SET_ACCOUNT";

export const REQUEST_ERROR = "REQ_ERROR";

export const RESET_ERROR_MESSAGE = "RESET_ERROR";

export const SERVER_ERROR = "SERVER_ERROR";

export const SERVER_ERRROR_MESSAGE = "SERVER ERROR";

export const RESET_SERVER_MESSAGE = "RESET_SERVER_MESSAGE";

export const SUCCESS_MESSAGE = "DECLINE_SUCCESS";

export const RESET_SUCCESS_MESSAGE = "RESET_SUCCESS_MESSAGE";
